Repository TokamakUI/Tokamak, pull requests merged in 2020-06, with the labels that each got.

#112 Add ZStack and modifier support for setting zIndex
  Sources/TokamakCore/Modifiers/ModifiedContent.swift
  Sources/TokamakCore/Modifiers/ViewModifier.swift
  Sources/TokamakCore/Modifiers/zIndex.swift
  Sources/TokamakCore/Views/TupleView.swift
  Sources/TokamakCore/Views/ZStack.swift
  Sources/TokamakDOM/Modifiers/ViewModifier.swift
  Sources/TokamakDOM/Modifiers/_ViewModifier_Content.swift
  Sources/TokamakDOM/Views/ZStack.swift
  Sources/TokamakDemo/main.swift
Labels: SwiftUI compatibility

#115 Fix HStack divs without flexbox
  Sources/TokamakCore/Views/HStack.swift
  Sources/TokamakCore/Views/VStack.swift
  Sources/TokamakCore/Views/ZStack.swift
  Sources/TokamakDOM/Views/HStack.swift
  Sources/TokamakDOM/Views/ZStack.swift
Labels: bug

#114 Add support for Text Modifiers
  README.md
  Sources/TokamakCore/Environment/Environment.swift
  Sources/TokamakCore/Environment/EnvironmentKey.swift
  Sources/TokamakCore/Environment/EnvironmentValues.swift
  Sources/TokamakCore/Modifiers/ViewModifier.swift
  Sources/TokamakCore/Tokens/Color.swift
  Sources/TokamakCore/Tokens/Font.swift
  Sources/TokamakCore/Tokens/LineBreakMode.swift
  Sources/TokamakCore/Tokens/Rectangle.swift
  Sources/TokamakCore/Tokens/TextAlignment.swift
  Sources/TokamakCore/Views/Text.swift
  Sources/TokamakDOM/Tokens/Tokens.swift
  Sources/TokamakDOM/Views/HTML.swift
  Sources/TokamakDOM/Views/Text.swift
  Sources/TokamakDemo/main.swift
Labels: SwiftUI compatibility

#117 Update DOM node properties and listeners on renderer update
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakDOM/Views/HTML.swift
Labels: bug

#118 Add layout modifiers
  Sources/TokamakCore/Modifiers/FlexFrameLayout.swift
  Sources/TokamakCore/Modifiers/FrameLayout.swift
  Sources/TokamakCore/Modifiers/PaddingLayout.swift
  Sources/TokamakCore/Tokens/Edge.swift
  Sources/TokamakDOM/Modifiers/LayoutModifiers.swift
  Sources/TokamakDemo/SVGCircle.swift
  Sources/TokamakDemo/main.swift
Labels: SwiftUI compatibility

#116 Add TextField, SecureField, and a progress document
  .gitignore
  Sources/TokamakCore/Views/SecureField.swift
  Sources/TokamakCore/Views/TextField.swift
  Sources/TokamakDOM/Views/SecureField.swift
  Sources/TokamakDOM/Views/TextField.swift
  Sources/TokamakDemo/TextFieldDemo.swift
  Sources/TokamakDemo/main.swift
  docs/progress.md
Labels: SwiftUI compatibility

#123 Check whether PRs have labels with GitHub Actions
  .github/workflows/label.yml
Labels: continuous integration

#124 Re-enable linting with Danger
  .github/workflows/danger.yml
  Dangerfile.swift
Labels: continuous integration

#122 Add Spacer support
  Sources/TokamakCore/Views/Spacer.swift
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakDOM/Views/HStack.swift
  Sources/TokamakDOM/Views/Spacer.swift
  Sources/TokamakDOM/Views/VStack.swift
  Sources/TokamakDemo/SpacerDemo.swift
  Sources/TokamakDemo/TextDemo.swift
  Sources/TokamakDemo/main.swift
  docs/progress.md
Labels: SwiftUI compatibility

#128 Add ScrollView
  Sources/TokamakCore/Tokens/Axis.swift
  Sources/TokamakCore/Views/ScrollView.swift
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakDOM/Modifiers/LayoutModifiers.swift
  Sources/TokamakDOM/Resources/TokamakStyles.swift
  Sources/TokamakDOM/Views/HStack.swift
  Sources/TokamakDOM/Views/ScrollView.swift
  Sources/TokamakDOM/Views/VStack.swift
  Sources/TokamakDemo/main.swift
  docs/progress.md
Labels: SwiftUI compatibility

#127 Use proxy types for package private properties
  Sources/TokamakCore/Views/Button.swift
  Sources/TokamakCore/Views/SecureField.swift
  Sources/TokamakCore/Views/Text.swift
  Sources/TokamakCore/Views/TextField.swift
  Sources/TokamakCore/Views/TupleView.swift
  Sources/TokamakDOM/Views/Button.swift
  Sources/TokamakDOM/Views/SecureField.swift
  Sources/TokamakDOM/Views/Text.swift
  Sources/TokamakDOM/Views/TextField.swift
Labels: refactor
