Repository TokamakUI/Tokamak, pull requests merged in 2020-07, with the labels that each got.

#133 Add logo to README.md
  README.md
  docs/logo-header.png
Labels: documentation

#135 Implement Environment
  Sources/TokamakCore/Environment/Environment.swift
  Sources/TokamakCore/Environment/EnvironmentKey.swift
  Sources/TokamakCore/MountedComponents/MountedCompositeView.swift
  Sources/TokamakCore/MountedComponents/MountedHostView.swift
  Sources/TokamakCore/MountedComponents/MountedView.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakDOM/Environment/Environment.swift
  Sources/TokamakDemo/EnvironmentDemo.swift
  Sources/TokamakDemo/main.swift
Labels: SwiftUI compatibility

#138 Conditionally import SwiftUI in README.md example
  README.md
Labels: documentation

#137 Add "Modular structure" section to `README.md`
  README.md
Labels: documentation

#140 Credit SwiftWebUI in a special way in README.md
  README.md
Labels: documentation

#125 Add TextFieldStyle
  Sources/TokamakCore/CGStubs.swift
  Sources/TokamakCore/Styles/TextFieldStyle.swift
  Sources/TokamakCore/Views/TextField.swift
  Sources/TokamakDOM/Views/TextField.swift
  Sources/TokamakDemo/TextFieldDemo.swift
  Sources/TokamakDemo/main.swift
  docs/progress.md
Labels: SwiftUI compatibility

#146 Allow @Environment on all MountedViews
  Sources/TokamakCore/MountedViews/MountedView.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakCore/Views/Text.swift
  Sources/TokamakDOM/Views/Text.swift
  Sources/TokamakDemo/main.swift
Labels: bug

#144 Add doc comment to the ViewDeferredToRenderer protocol
  Sources/TokamakCore/Views/View.swift
Labels: documentation

#145 Add AppearanceActionModifier, onAppear/onDisappear
  Sources/TokamakCore/Modifiers/AppearanceActionModifier.swift
  Sources/TokamakCore/Modifiers/ViewModifier.swift
  Sources/TokamakCore/MountedViews/MountedCompositeView.swift
  Sources/TokamakDOM/Modifiers/_ViewModifier_Content.swift
  Sources/TokamakDemo/Counter.swift
Labels: SwiftUI compatibility

#153 Use a range instead of an array in ForEach
  Sources/TokamakCore/Views/ForEach.swift
  Sources/TokamakDemo/ForEachDemo.swift
Labels: refactor

#151 Update AnyView status in progress.md
  docs/progress.md
Labels: SwiftUI compatibility

#150 Add Group implementation
  Sources/TokamakCore/Views/Group.swift
  Sources/TokamakDOM/Views/Group.swift
  Sources/TokamakDemo/TokamakDemo.swift
  docs/progress.md
Labels: SwiftUI compatibility

#157 Update Acknowledgments section in README.md
  README.md
Labels: documentation

#160 Use `let` instead of `var` in `TextFieldStyleKey: EnvironmentKey`
  Sources/TokamakCore/Styles/TextFieldStyle.swift
Labels: refactor

#162 ViewBuilder buildIf fix
  Sources/TokamakCore/Views/ViewBuilder.swift
Labels: bug

#147 Add List and related Views
  Sources/TokamakCore/Modifiers/Effects/GeometryEffect.swift
  Sources/TokamakCore/Modifiers/Effects/RotationEffect.swift
  Sources/TokamakCore/Modifiers/ModifiedContent.swift
  Sources/TokamakCore/Styles/ListStyle.swift
  Sources/TokamakCore/Styles/OutlineGroupStyle.swift
  Sources/TokamakCore/Views/AnyView.swift
  Sources/TokamakCore/Views/DisclosureGroup.swift
  Sources/TokamakCore/Views/Divider.swift
  Sources/TokamakCore/Views/List.swift
  Sources/TokamakCore/Views/OutlineGroup.swift
  Sources/TokamakCore/Views/Section.swift
  Sources/TokamakDOM/Modifiers/Effects/RotationEffect.swift
  Sources/TokamakDOM/Resources/TokamakStyles.swift
  Sources/TokamakDOM/Styles/Styles.swift
  Sources/TokamakDOM/Views/DisclosureGroup.swift
  Sources/TokamakDOM/Views/Divider.swift
  Sources/TokamakDOM/Views/List.swift
  Sources/TokamakDemo/ListDemo.swift
  Sources/TokamakDemo/OutlineGroupDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
  docs/progress.md
Labels: SwiftUI compatibility

#164 Build macOS demo on CI
  .github/workflows/ci.yml
  Sources/TokamakDemo/ListDemo.swift
  Sources/TokamakDemo/OutlineGroupDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
  TokamakDemo Native/TokamakDemo Native.xcodeproj/project.pbxproj
Labels: continuous integration

#165 Allow modified views to fill their parent if a child requires it
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakDOM/Modifiers/LayoutModifiers.swift
  Sources/TokamakDOM/Modifiers/ViewModifier.swift
  Sources/TokamakDOM/Modifiers/_ViewModifier_Content.swift
  Sources/TokamakDOM/Shapes/Shape.swift
Labels: bug

#172 Extend Path to match SwiftUI
  Sources/TokamakCore/CGStubs.swift
  Sources/TokamakCore/Shapes/Path.swift
  Sources/TokamakCore/Shapes/Rectangle.swift
  Sources/TokamakCore/Tokens/Angle.swift
  Sources/TokamakDOM/Shapes/Path.swift
  Sources/TokamakDOM/Shapes/Shape.swift
  Sources/TokamakDOM/Shapes/_ShapeView.swift
  Sources/TokamakDemo/PathDemo.swift
  Sources/TokamakDemo/SVGCircle.swift
  Sources/TokamakDemo/TokamakDemo.swift
  TokamakDemo Native/TokamakDemo Native.xcodeproj/project.pbxproj
Labels: SwiftUI compatibility

#174 Add Text concatenation via + operator
  Sources/TokamakCore/Views/Text.swift
  Sources/TokamakDOM/Views/SecureField.swift
  Sources/TokamakDOM/Views/Text.swift
  Sources/TokamakDOM/Views/TextField.swift
  Sources/TokamakDemo/TextDemo.swift
Labels: SwiftUI compatibility

#177 Extend Color to match SwiftUI
  Sources/TokamakCore/Tokens/Color.swift
  Sources/TokamakDemo/ColorDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
  TokamakDemo Native/TokamakDemo Native.xcodeproj/project.pbxproj
Labels: SwiftUI compatibility

#178 Implement `static func Binding<Value>.constant`
  Sources/TokamakCore/Binding.swift
  Sources/TokamakDOM/Views/SecureField.swift
  Sources/TokamakDOM/Views/TextField.swift
Labels: SwiftUI compatibility

#179 Add LazyHGrid and LazyVGrid
  Sources/TokamakCore/Tokens/GridItem.swift
  Sources/TokamakCore/Views/LazyHGrid.swift
  Sources/TokamakCore/Views/LazyVGrid.swift
  Sources/TokamakCore/Views/ScrollView.swift
  Sources/TokamakDOM/Tokens/Tokens.swift
  Sources/TokamakDOM/Views/LazyHGrid.swift
  Sources/TokamakDOM/Views/LazyVGrid.swift
  Sources/TokamakDOM/Views/SecureField.swift
  Sources/TokamakDOM/Views/Spacer.swift
  Sources/TokamakDOM/Views/TextField.swift
  Sources/TokamakDemo/GridDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
  TokamakDemo Native/TokamakDemo Native.xcodeproj/project.pbxproj
  docs/progress.md
Labels: SwiftUI compatibility

#187 Mention `#webassembly` SwiftPM Slack channel in README.md
  README.md
Labels: documentation

#168 Avoid AnyView in the Counter code
  .github/workflows/ci.yml
  README.md
  Sources/TokamakCore/Views/View.swift
  Sources/TokamakCore/Views/ViewBuilder.swift
  Sources/TokamakDOM/Views/SecureField.swift
  Sources/TokamakDOM/Views/TextField.swift
  Sources/TokamakDemo/Counter.swift
  Sources/TokamakDemo/OutlineGroupDemo.swift
Labels: documentation

#171 Add @ObservedObject implementation
  Package.resolved
  Package.swift
  Sources/TokamakCore/MountedViews/MountedCompositeView.swift
  Sources/TokamakCore/ObservedObject.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakDOM/Views/HTML.swift
  Sources/TokamakDemo/Counter.swift
  Sources/TokamakDemo/TokamakDemo.swift
Labels: SwiftUI compatibility

#191 Allow non-consecutive state variables
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakDemo/ColorDemo.swift
Labels: bug

#170 Add @EnvironmentObject
  Sources/TokamakCore/Environment/Environment.swift
  Sources/TokamakCore/Environment/EnvironmentObject.swift
  Sources/TokamakCore/Environment/EnvironmentValues.swift
  Sources/TokamakCore/MountedViews/MountedHostView.swift
  Sources/TokamakCore/MountedViews/MountedView.swift
  Sources/TokamakDOM/Environment/Environment.swift
  Sources/TokamakDemo/EnvironmentDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
Labels: SwiftUI compatibility

#193 Organize all the re-exports into a single file
  Sources/TokamakDOM/Core.swift
  Sources/TokamakDOM/Environment/Environment.swift
  Sources/TokamakDOM/Modifiers/ViewModifier.swift
  Sources/TokamakDOM/Shapes/Path.swift
  Sources/TokamakDOM/Shapes/Shape.swift
  Sources/TokamakDOM/Shapes/_ShapeView.swift
  Sources/TokamakDOM/Styles/Styles.swift
  Sources/TokamakDOM/Tokens/Tokens.swift
  Sources/TokamakDOM/Views/Button.swift
  Sources/TokamakDOM/Views/DisclosureGroup.swift
  Sources/TokamakDOM/Views/Divider.swift
  Sources/TokamakDOM/Views/ForEach.swift
  Sources/TokamakDOM/Views/Group.swift
  Sources/TokamakDOM/Views/HStack.swift
  Sources/TokamakDOM/Views/HTML.swift
  Sources/TokamakDOM/Views/LazyHGrid.swift
  Sources/TokamakDOM/Views/LazyVGrid.swift
  Sources/TokamakDOM/Views/List.swift
  Sources/TokamakDOM/Views/Picker.swift
  Sources/TokamakDOM/Views/ScrollView.swift
  Sources/TokamakDOM/Views/SecureField.swift
  Sources/TokamakDOM/Views/Spacer.swift
  Sources/TokamakDOM/Views/Text.swift
  Sources/TokamakDOM/Views/TextField.swift
  Sources/TokamakDOM/Views/VStack.swift
  Sources/TokamakDOM/Views/ZStack.swift
Labels: refactor

#196 Add `UIColor` stub and new `Color.init(_:UIColor)`
  Sources/TokamakCore/Stubs/CGStubs.swift
  Sources/TokamakCore/Stubs/UIColor.swift
  Sources/TokamakCore/Tokens/Color.swift
Labels: SwiftUI compatibility

#194 Move view files to separate subdirectories
  Sources/TokamakCore/State/Binding.swift
  Sources/TokamakCore/State/ObservedObject.swift
  Sources/TokamakCore/State/State.swift
  Sources/TokamakCore/Views/Buttons/Button.swift
  Sources/TokamakCore/Views/Containers/DisclosureGroup.swift
  Sources/TokamakCore/Views/Containers/ForEach.swift
  Sources/TokamakCore/Views/Containers/Group.swift
  Sources/TokamakCore/Views/Containers/List.swift
  Sources/TokamakCore/Views/Containers/OutlineGroup.swift
  Sources/TokamakCore/Views/Containers/Section.swift
  Sources/TokamakCore/Views/Containers/TupleView.swift
  Sources/TokamakCore/Views/Layout/HStack.swift
  Sources/TokamakCore/Views/Layout/LazyHGrid.swift
  Sources/TokamakCore/Views/Layout/LazyVGrid.swift
  Sources/TokamakCore/Views/Layout/ScrollView.swift
  Sources/TokamakCore/Views/Layout/VStack.swift
  Sources/TokamakCore/Views/Layout/ZStack.swift
  Sources/TokamakCore/Views/Selectors/Picker.swift
  Sources/TokamakCore/Views/Spacers/Divider.swift
  Sources/TokamakCore/Views/Spacers/Spacer.swift
  Sources/TokamakCore/Views/Text/SecureField.swift
  Sources/TokamakCore/Views/Text/Text.swift
  Sources/TokamakCore/Views/Text/TextField.swift
  Sources/TokamakDOM/Views/Buttons/Button.swift
  Sources/TokamakDOM/Views/Containers/DisclosureGroup.swift
  Sources/TokamakDOM/Views/Containers/List.swift
  Sources/TokamakDOM/Views/Layout/HStack.swift
  Sources/TokamakDOM/Views/Layout/LazyHGrid.swift
  Sources/TokamakDOM/Views/Layout/LazyVGrid.swift
  Sources/TokamakDOM/Views/Layout/ScrollView.swift
  Sources/TokamakDOM/Views/Layout/VStack.swift
  Sources/TokamakDOM/Views/Layout/ZStack.swift
  Sources/TokamakDOM/Views/Selectors/Picker.swift
  Sources/TokamakDOM/Views/Spacers/Divider.swift
  Sources/TokamakDOM/Views/Spacers/Spacer.swift
  Sources/TokamakDOM/Views/Text/SecureField.swift
  Sources/TokamakDOM/Views/Text/Text.swift
  Sources/TokamakDOM/Views/Text/TextField.swift
Labels: refactor

#201 Bump JavaScriptKit to 0.5.0
  Package.resolved
  Package.swift
Labels: bug, dependencies

#205 Update "Requirements" and "Getting started" README sections
  README.md
Labels: documentation

#206 Fix typo in `TokamakDemo.swift`
  Sources/TokamakDemo/TokamakDemo.swift
Labels: refactor

#207 Warn against beta versions of Xcode in README.md
  README.md
Labels: bug, documentation

#213 Implement `DynamicProperty`
  Sources/TokamakCore/App/AppStorage.swift
  Sources/TokamakCore/App/Scenes/SceneStorage.swift
  Sources/TokamakCore/DynamicProperty.swift
  Sources/TokamakCore/Environment/Environment.swift
  Sources/TokamakCore/Environment/EnvironmentObject.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakCore/State/Binding.swift
  Sources/TokamakCore/State/ObservedObject.swift
  Sources/TokamakCore/State/State.swift
Labels: SwiftUI compatibility, bug

#215 Generalize style and environment in `DOMRenderer`
  Sources/TokamakCore/Styles/ToggleStyle.swift
  Sources/TokamakDOM/DOMNode.swift
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakDOM/Resources/TokamakStyles.swift
Labels: refactor

#219 Unify code of `MountedApp`/`MountedCompositeView`
  Sources/TokamakCore/App/_AnyApp.swift
  Sources/TokamakCore/App/_AnyScene.swift
  Sources/TokamakCore/MountedViews/MountedApp.swift
  Sources/TokamakCore/MountedViews/MountedCompositeElement.swift
  Sources/TokamakCore/MountedViews/MountedCompositeView.swift
  Sources/TokamakCore/MountedViews/MountedElement.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakDOM/DOMRenderer.swift
Labels: refactor

#210 Implement `SidebarListStyle`
  NativeDemo/TokamakDemo.xcodeproj/project.pbxproj
  Sources/TokamakCore/Styles/ListStyle.swift
  Sources/TokamakCore/Views/Containers/List.swift
  Sources/TokamakDOM/Core.swift
  Sources/TokamakDOM/Views/Containers/List.swift
  Sources/TokamakDemo/AppStorageDemo.swift
  Sources/TokamakDemo/SidebarDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
Labels: SwiftUI compatibility

#217 Add `DefaultApp` type to simplify `DOMRenderer.init`
  Sources/TokamakCore/App/App.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakDOM/App.swift
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakDOM/Views/HTML.swift
Labels: refactor

#223 Fix environment changes causing remounted scenes with lost state
  Sources/TokamakCore/App/Scenes/Scene.swift
  Sources/TokamakCore/App/Scenes/WindowGroup.swift
  Sources/TokamakCore/App/_AnyScene.swift
  Sources/TokamakCore/MountedViews/MountedApp.swift
  Sources/TokamakCore/MountedViews/MountedCompositeElement.swift
  Sources/TokamakCore/MountedViews/MountedCompositeView.swift
  Sources/TokamakCore/MountedViews/MountedElement.swift
  Sources/TokamakCore/MountedViews/MountedEmptyView.swift
  Sources/TokamakCore/MountedViews/MountedHostView.swift
  Sources/TokamakCore/MountedViews/MountedScene.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakCore/Views/AnyView.swift
  Sources/TokamakDemo/main.swift
Labels: bug
