Repository TokamakUI/Tokamak, pull requests merged in 2020-11, with the labels that each got.

#276 Add Link view, update JavaScriptKit to 0.8.0
  .swift-version
  Package.swift
  Sources/TokamakCore/Views/Buttons/Link.swift
  Sources/TokamakStaticHTML/Core.swift
  Sources/TokamakStaticHTML/Modifiers/LayoutModifiers.swift
  Sources/TokamakStaticHTML/Resources/TokamakStyles.swift
  Sources/TokamakStaticHTML/Views/Buttons/Link.swift
Labels: enhancement

#295 Allow tests to be run on macOS
  .github/workflows/ci.yml
  Package.resolved
  Package.swift
  Sources/TokamakDemo/URLHashDemo.swift
  Tests/TokamakTests/ColorTests.swift
Labels: continuous integration, test suite

#297 Xcode compatibility
  .gitignore
  .swift-version
  Package.resolved
  Package.swift
  Sources/TokamakTestRenderer/TestRenderer.swift
Labels: enhancement

#298 Bump version to 0.5.0, update `CHANGELOG.md`
  CHANGELOG.md
Labels: documentation

#299 Allow use of Combine to enable Xcode autocomplete
  Sources/TokamakDOM/JSScheduler.swift
Labels: SwiftUI compatibility

#300 Update Package.resolved
  Package.resolved
Labels: dependencies

#301 Pass sibling to `Renderer.mount`, fix update order
  .github/workflows/ci.yml
  Sources/TokamakCore/MountedViews/MountedApp.swift
  Sources/TokamakCore/MountedViews/MountedCompositeView.swift
  Sources/TokamakCore/MountedViews/MountedElement.swift
  Sources/TokamakCore/MountedViews/MountedEmptyView.swift
  Sources/TokamakCore/MountedViews/MountedHostView.swift
  Sources/TokamakCore/MountedViews/MountedScene.swift
  Sources/TokamakCore/Renderer.swift
  Sources/TokamakCore/Views/View.swift
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakDOM/JSScheduler.swift
  Sources/TokamakStaticHTML/StaticRenderer.swift
  Sources/TokamakTestRenderer/TestRenderer.swift
  Tests/LinuxMain.swift
  Tests/TokamakTests/XCTestManifests.swift
Labels: bug, refactor

#304 Use `JSScheduler` from `OpenCombineJS` package
  Package.resolved
  Package.swift
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakDOM/JSScheduler.swift
Labels: dependencies

#308 Use latest macOS and Xcode on CI
  .github/workflows/ci.yml
Labels: continuous integration

#309 Fix update of `checked` property of checkbox input
  Sources/TokamakDOM/DOMNode.swift
  Sources/TokamakDOM/Styles/ToggleStyle.swift
  Sources/TokamakStaticHTML/Views/HTML.swift
Labels: bug

#311 Remove unused Dangerfile.swift
  Dangerfile.swift
Labels: continuous integration
