Repository TokamakUI/Tokamak, pull requests merged in 2020-12, with the labels that each got.

#307 Add Preferences
  NativeDemo/TokamakDemo.xcodeproj/project.pbxproj
  Package.swift
  Sources/TokamakCore/Environment/EnvironmentKey.swift
  Sources/TokamakCore/Modifiers/Navigation.swift
  Sources/TokamakCore/Modifiers/StyleModifiers.swift
  Sources/TokamakCore/Modifiers/ViewModifier.swift
  Sources/TokamakCore/MountedViews/MountedApp.swift
  Sources/TokamakCore/MountedViews/MountedCompositeElement.swift
  Sources/TokamakCore/MountedViews/MountedCompositeView.swift
  Sources/TokamakCore/MountedViews/MountedElement.swift
  Sources/TokamakCore/MountedViews/MountedEmptyView.swift
  Sources/TokamakCore/MountedViews/MountedHostView.swift
  Sources/TokamakCore/MountedViews/MountedScene.swift
  Sources/TokamakCore/Preferences/PreferenceKey.swift
  Sources/TokamakCore/Preferences/_PreferenceActionModifier.swift
  Sources/TokamakCore/Preferences/_PreferenceReadingView.swift
  Sources/TokamakCore/Preferences/_PreferenceTransformModifier.swift
  Sources/TokamakCore/Preferences/_PreferenceWritingModifier.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakCore/Tokens/Color.swift
  Sources/TokamakCore/Tokens/ColorScheme.swift
  Sources/TokamakCore/Views/Navigation/NavigationLink.swift
  Sources/TokamakCore/Views/Navigation/NavigationView.swift
  Sources/TokamakCore/Views/Text/Text.swift
  Sources/TokamakDOM/Core.swift
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakDemo/PreferenceKeyDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
  Sources/TokamakStaticHTML/Modifiers/ModifiedContent.swift
  Sources/TokamakStaticHTML/Views/Navigation/NavigationView.swift
Labels: SwiftUI compatibility

#310 Add @kateinoigakukun to the list of maintainers
  README.md
Labels: documentation

#328 Add `PreviewProvider` protocol
  Sources/TokamakCore/PreviewProvider.swift
  Sources/TokamakDOM/Core.swift
  Sources/TokamakDemo/ToggleDemo.swift
  Sources/TokamakStaticHTML/Core.swift
Labels: SwiftUI compatibility

#331 Added some missing TokamakDOM/Core type typealiases
  Sources/TokamakDOM/Core.swift
Labels: enhancement

#332 Update script injection code in `README.md`
  README.md
Labels: bug, documentation

#341 Remove extra `path` element
  Sources/TokamakCore/MountedViews/MountedElement.swift
  Sources/TokamakCore/MountedViews/MountedScene.swift
  Sources/TokamakCore/Views/Selectors/Picker.swift
  Sources/TokamakDOM/Core.swift
  Sources/TokamakDemo/ColorDemo.swift
  Sources/TokamakStaticHTML/Modifiers/ModifiedContent.swift
  Sources/TokamakStaticHTML/Shapes/Path.swift
Labels: bug

#343 Add `Image` implementation to the GTK renderer
  Package.swift
  Sources/TokamakGTK/Core.swift
  Sources/TokamakGTK/Views/Image.swift
  Sources/TokamakGTKDemo/logo-header.png
  Sources/TokamakGTKDemo/main.swift
Labels: GTK renderer, SwiftUI compatibility

#344 Add `background` modifier, support widget updates in `WidgetView`
  Sources/TokamakGTK/Modifiers/LayoutModifiers.swift
  Sources/TokamakGTK/Modifiers/WidgetModifier.swift
  Sources/TokamakGTK/Widget.swift
  Sources/TokamakGTKDemo/main.swift
Labels: GTK renderer, SwiftUI compatibility

#345 Allow gtk modifiers to be expressed as css attributes.
  Sources/TokamakGTK/Modifiers/LayoutModifiers.swift
  Sources/TokamakGTK/Modifiers/WidgetModifier.swift
  Sources/TokamakGTKDemo/main.swift
Labels: GTK renderer
