Repository TokamakUI/Tokamak, pull requests merged in 2020-08, with the labels that each got.

#227 Remove `DefaultApp`, make `DOMRenderer` internal
  README.md
  Sources/TokamakCore/Target.swift
  Sources/TokamakDOM/App.swift
  Sources/TokamakDOM/DOMNode.swift
  Sources/TokamakDOM/DOMRenderer.swift
Labels: documentation, refactor

#234 Fix tests, move `DefaultButtonStyle` to TokamakCore
  Sources/TokamakCore/Styles/ButtonStyle.swift
  Sources/TokamakCore/Views/Buttons/Button.swift
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakDOM/Styles/ButtonStyle.swift
  Sources/TokamakTestRenderer/TestView.swift
  Tests/TokamakTests/ReconcilerTests.swift
Labels: test suite

#232 Add `redacted` modifier
  NativeDemo/TokamakDemo.xcodeproj/project.pbxproj
  Sources/TokamakCore/Modifiers/RedactionReasons.swift
  Sources/TokamakCore/Views/Text/Text.swift
  Sources/TokamakDemo/RedactDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
  Sources/TokamakStaticHTML/Resources/TokamakStyles.swift
  Sources/TokamakStaticHTML/Views/Text/Text.swift
Labels: SwiftUI compatibility

#240 Add `_targetRef` and `_domRef` modifiers
  Sources/TokamakCore/Modifiers/AppearanceActionModifier.swift
  Sources/TokamakCore/Modifiers/StyleModifiers.swift
  Sources/TokamakCore/Modifiers/ZIndexModifier.swift
  Sources/TokamakCore/MountedViews/MountedCompositeView.swift
  Sources/TokamakCore/MountedViews/MountedHostView.swift
  Sources/TokamakCore/Shapes/Shape.swift
  Sources/TokamakCore/Shapes/ShapeModifiers.swift
  Sources/TokamakCore/State/TargetRef.swift
  Sources/TokamakCore/Tokens/Edge.swift
  Sources/TokamakDOM/DOMRef.swift
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakDemo/DOMRefDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
Labels: API design, enhancement

#246 Remove some `AnyView` in the `List` implementation
  Sources/TokamakCore/Views/Containers/List.swift
Labels: refactor

#243 Split demo list into sections
  Sources/TokamakDemo/RedactDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
Labels: enhancement

#250 Update to the latest version of SwiftFormat
  .swiftformat
  .swiftlint.yml
  .vscode/settings.json
  README.md
  Sources/TokamakCore/App/AppStorage.swift
  Sources/TokamakCore/App/Scenes/SceneBuilder.swift
  Sources/TokamakCore/App/Scenes/SceneStorage.swift
  Sources/TokamakCore/App/Scenes/WindowGroup.swift
  Sources/TokamakCore/App/_AnyApp.swift
  Sources/TokamakCore/Environment/EnvironmentObject.swift
  Sources/TokamakCore/Modifiers/AppearanceActionModifier.swift
  Sources/TokamakCore/Modifiers/Effects/ClipEffect.swift
  Sources/TokamakCore/Modifiers/FlexFrameLayout.swift
  Sources/TokamakCore/Modifiers/FrameLayout.swift
  Sources/TokamakCore/Modifiers/ModifiedContent.swift
  Sources/TokamakCore/Modifiers/StyleModifiers.swift
  Sources/TokamakCore/MountedViews/MountedCompositeElement.swift
  Sources/TokamakCore/MountedViews/MountedElement.swift
  Sources/TokamakCore/MountedViews/MountedScene.swift
  Sources/TokamakCore/Shapes/Path.swift
  Sources/TokamakCore/Shapes/Rectangle.swift
  Sources/TokamakCore/Shapes/Shape.swift
  Sources/TokamakCore/Shapes/ShapeModifiers.swift
  Sources/TokamakCore/Shapes/StrokeStyle.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakCore/State/State.swift
  Sources/TokamakCore/Stubs/CGStubs.swift
  Sources/TokamakCore/Styles/ListStyle.swift
  Sources/TokamakCore/Tokens/Color.swift
  Sources/TokamakCore/Tokens/Font.swift
  Sources/TokamakCore/Tokens/GridItem.swift
  Sources/TokamakCore/Views/Containers/DisclosureGroup.swift
  Sources/TokamakCore/Views/Containers/ForEach.swift
  Sources/TokamakCore/Views/Containers/List.swift
  Sources/TokamakCore/Views/Containers/OutlineGroup.swift
  Sources/TokamakCore/Views/Containers/TupleView.swift
  Sources/TokamakCore/Views/Layout/LazyHGrid.swift
  Sources/TokamakCore/Views/Layout/LazyVGrid.swift
  Sources/TokamakCore/Views/Layout/ScrollView.swift
  Sources/TokamakCore/Views/Selectors/Picker.swift
  Sources/TokamakCore/Views/Text/Text.swift
  Sources/TokamakCore/Views/ViewBuilder.swift
  Sources/TokamakDOM/Views/Containers/DisclosureGroup.swift
  Sources/TokamakDemo/ColorDemo.swift
  Sources/TokamakDemo/PathDemo.swift
  Sources/TokamakDemo/PickerDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
  Sources/TokamakStaticHTML/Modifiers/ViewModifier.swift
  Sources/TokamakStaticHTML/Modifiers/_ViewModifier_Content.swift
  Sources/TokamakStaticHTML/Shapes/Path.swift
  Sources/TokamakStaticHTML/Shapes/Shape.swift
  Sources/TokamakStaticHTML/Views/Containers/List.swift
  Sources/TokamakTestRenderer/TestView.swift
Labels: documentation, refactor

#249 Fix color scheme observer crashes in Safari
  Sources/TokamakDOM/App/ColorSchemeObserver.swift
Labels: bug

#252 Use the latest 5.3 snapshot in `.swift-version`
  .swift-version
  Package.resolved
  Package.swift
Labels: dependencies

#251 Link to the renderers guide from `README.md`
  README.md
  docs/Building a Renderer/1 Renderers in Tokamak.md
  docs/Building a Renderer/2 Understanding Renderers.md
  docs/Building a Renderer/3 TokamakStatic Setup.md
  docs/Building a Renderer/4 Building the Target.md
  docs/Building a Renderer/5 Building the Renderer.md
  docs/Building a Renderer/6 Providing platform-specific primitives.md
  docs/RenderersGuide.md
Labels: documentation

#241 Add default dark styles for Views
  Sources/TokamakCore/Modifiers/FlexFrameLayout.swift
  Sources/TokamakCore/Modifiers/ModifiedContent.swift
  Sources/TokamakCore/Modifiers/StyleModifiers.swift
  Sources/TokamakCore/Shapes/ModifiedShapes.swift
  Sources/TokamakCore/Shapes/Shape.swift
  Sources/TokamakCore/Styles/NavigationLinkStyle.swift
  Sources/TokamakCore/Tokens/Color.swift
  Sources/TokamakCore/Views/Containers/ForEach.swift
  Sources/TokamakCore/Views/Containers/List.swift
  Sources/TokamakCore/Views/Containers/Section.swift
  Sources/TokamakCore/Views/Navigation/NavigationLink.swift
  Sources/TokamakCore/Views/Navigation/NavigationView.swift
  Sources/TokamakCore/Views/Spacers/Divider.swift
  Sources/TokamakCore/Views/Text/Text.swift
  Sources/TokamakDOM/App/App.swift
  Sources/TokamakDOM/App/ColorSchemeObserver.swift
  Sources/TokamakDOM/Views/Buttons/Button.swift
  Sources/TokamakDOM/Views/DynamicHTML.swift
  Sources/TokamakDOM/Views/Navigation/NavigationLink.swift
  Sources/TokamakDOM/Views/Selectors/Picker.swift
  Sources/TokamakDOM/Views/Text/SecureField.swift
  Sources/TokamakDOM/Views/Text/TextField.swift
  Sources/TokamakDemo/ColorDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
  Sources/TokamakStaticHTML/Modifiers/LayoutModifiers.swift
  Sources/TokamakStaticHTML/Modifiers/ModifiedContent.swift
  Sources/TokamakStaticHTML/Modifiers/ViewModifier.swift
  Sources/TokamakStaticHTML/Resources/TokamakStyles.swift
  Sources/TokamakStaticHTML/Shapes/Shape.swift
  Sources/TokamakStaticHTML/Shapes/_ShapeView.swift
  Sources/TokamakStaticHTML/Tokens/BuiltinColors.swift
  Sources/TokamakStaticHTML/Tokens/Tokens.swift
  Sources/TokamakStaticHTML/Views/Containers/List.swift
  Sources/TokamakStaticHTML/Views/HTML.swift
  Sources/TokamakStaticHTML/Views/Navigation/NavigationView.swift
  Sources/TokamakStaticHTML/Views/Spacers/Divider.swift
  Sources/TokamakStaticHTML/Views/Text/Text.swift
  Tests/TokamakTests/ColorTests.swift
Labels: SwiftUI compatibility

#259 Fix `NavigationView` broken state after re-render
  Sources/TokamakCore/MountedViews/MountedCompositeElement.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakCore/State/ObservedObject.swift
Labels: bug

#260 Implement `StateObject` property wrapper
  Sources/TokamakCore/MountedViews/MountedCompositeElement.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakCore/State/ObservedObject.swift
  Sources/TokamakCore/State/State.swift
  Sources/TokamakCore/State/StateObject.swift
  Sources/TokamakCore/Views/Navigation/NavigationView.swift
  Sources/TokamakDOM/Core.swift
Labels: SwiftUI compatibility, bug

#262 Set versions of dependencies in `Package.swift`
  .github/workflows/ci.yml
  Package.resolved
  Package.swift
Labels: dependencies

#265 Add missing JavaScriptKit import to `README.md`
  README.md
Labels: documentation

#264 Remove Xcode 12 warning from README.md
  README.md
Labels: documentation

#228 Add `Slider` implementation
  NativeDemo/TokamakDemo Native.entitlements
  NativeDemo/TokamakDemo.xcodeproj/project.pbxproj
  Sources/TokamakCore/Views/Selectors/Slider.swift
  Sources/TokamakDOM/Core.swift
  Sources/TokamakDOM/Views/Selectors/Slider.swift
  Sources/TokamakDemo/SliderDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
  Sources/TokamakStaticHTML/Views/Layout/ScrollView.swift
  docs/progress.md
Labels: SwiftUI compatibility

#268 Fix the sizing of sliders
  Sources/TokamakDOM/Views/Selectors/Slider.swift
Labels: bug

#271 Allow non-body mount host node
  Sources/TokamakDOM/App/App.swift
Labels: enhancement
