Repository TokamakUI/Tokamak, pull requests merged in 2021-02, with the labels that each got.

#375 Add checks for metadata state
  Sources/TokamakCore/Reflection/Metadata/MetadataState.swift
  Sources/TokamakCore/Reflection/Metadata/StructMetadata.swift
  Sources/TokamakCoreBenchmark/main.swift
  Sources/TokamakStaticHTMLBenchmark/main.swift
Labels: refactor

#378 Simple Code Coverage analysis
  .github/workflows/codecov.yml
Labels: continuous integration

#380 Use immediate scheduler in TestRenderer
  .github/workflows/ci.yml
  LICENSE
  Sources/TokamakTestRenderer/TestRenderer.swift
  Tests/TokamakTests/ReconcilerTests.swift
Labels: continuous integration, test suite

#382 Make properties of CGPoint, CGSize and CGRect vars instead of lets
  Sources/TokamakCore/Stubs/CGStubs.swift
Labels: bug
