Repository TokamakUI/Tokamak, pull requests merged in 2021-05, with the labels that each got.

#398 Update `CHANGELOG.md` for the 0.7.0 release
  CHANGELOG.md
Labels: documentation

#401 Multiline Text and multilineTextAlignment(_:)
  Sources/TokamakCore/Tokens/TextAlignment.swift
  Sources/TokamakDemo/TextDemo.swift
  Sources/TokamakStaticHTML/Views/Text/Text.swift
Labels: SwiftUI compatibility, bug

#407 Fix DOMRenderer crash after DOM has been directly modified. (#326, #369)
  Sources/TokamakDOM/DOMRenderer.swift
Labels: bug
