Repository TokamakUI/Tokamak, pull requests merged in 2021-06, with the labels that each got.

#346 Sort attributes in HTML nodes when rendering
  Package.swift
  Sources/TokamakDOM/DOMNode.swift
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakDOM/Views/Buttons/Button.swift
  Sources/TokamakDOM/Views/DynamicHTML.swift
  Sources/TokamakStaticHTML/StaticRenderer.swift
  Sources/TokamakStaticHTML/Views/HTML.swift
  Sources/TokamakStaticHTML/Views/Spacers/Divider.swift
  Sources/TokamakStaticHTML/Views/Text/Text.swift
  Sources/TokamakStaticHTMLBenchmark/main.swift
  Sources/TokamakStaticHTMLDemo/ContentView.swift
  Sources/TokamakStaticHTMLDemo/main.swift
Labels: test suite

#409 Allow DOMRenderer to render buttons with non-Text labels (#403)
  Sources/TokamakDOM/Views/Buttons/Button.swift
  Sources/TokamakDemo/ButtonStyleDemo.swift
Labels: SwiftUI compatibility

#410 Fix spacers after DOMRenderer.update
  Sources/TokamakDOM/DOMRenderer.swift
Labels: bug

#411 Use `CGFloat`, `CGPoint`, `CGRect` from Foundation
  Sources/TokamakCore/Modifiers/Effects/ClipEffect.swift
  Sources/TokamakCore/Modifiers/Effects/GeometryEffect.swift
  Sources/TokamakCore/Modifiers/Effects/RotationEffect.swift
  Sources/TokamakCore/Modifiers/FlexFrameLayout.swift
  Sources/TokamakCore/Modifiers/FrameLayout.swift
  Sources/TokamakCore/Modifiers/PaddingLayout.swift
  Sources/TokamakCore/Modifiers/ShadowLayout.swift
  Sources/TokamakCore/Modifiers/StyleModifiers.swift
  Sources/TokamakCore/PreviewProvider.swift
  Sources/TokamakCore/Shapes/Ellipse.swift
  Sources/TokamakCore/Shapes/FixedRoundedRect.swift
  Sources/TokamakCore/Shapes/ModifiedShapes.swift
  Sources/TokamakCore/Shapes/Path.swift
  Sources/TokamakCore/Shapes/Rectangle.swift
  Sources/TokamakCore/Shapes/Shape.swift
  Sources/TokamakCore/Shapes/ShapeModifiers.swift
  Sources/TokamakCore/Shapes/StrokeStyle.swift
  Sources/TokamakCore/Shapes/TrimmedPath.swift
  Sources/TokamakCore/Stubs/CGStubs.swift
  Sources/TokamakCore/Tokens/Edge.swift
  Sources/TokamakCore/Tokens/Font.swift
  Sources/TokamakCore/Tokens/GridItem.swift
  Sources/TokamakCore/Tokens/UnitPoint.swift
  Sources/TokamakCore/Views/Containers/Section.swift
  Sources/TokamakCore/Views/Layout/GeometryReader.swift
  Sources/TokamakCore/Views/Layout/HStack.swift
  Sources/TokamakCore/Views/Layout/LazyHGrid.swift
  Sources/TokamakCore/Views/Layout/LazyVGrid.swift
  Sources/TokamakCore/Views/Layout/VStack.swift
  Sources/TokamakCore/Views/Layout/ZStack.swift
  Sources/TokamakCore/Views/Spacers/Spacer.swift
  Sources/TokamakCore/Views/Text/Text.swift
  Sources/TokamakDOM/Core.swift
  Sources/TokamakDOM/Views/Layout/GeometryReader.swift
  Sources/TokamakDemo/PathDemo.swift
  Sources/TokamakDemo/TextDemo.swift
  Sources/TokamakGTK/Core.swift
  Sources/TokamakGTK/Shapes/Shape.swift
  Sources/TokamakGTK/Views/Stack.swift
  Sources/TokamakStaticHTML/Core.swift
  Sources/TokamakStaticHTML/Modifiers/LayoutModifiers.swift
  Sources/TokamakStaticHTML/Shapes/Path.swift
  Sources/TokamakStaticHTML/Views/Spacers/Spacer.swift
  Sources/TokamakStaticHTML/Views/Text/Text.swift
Labels: SwiftUI compatibility

#253 Attempt `padding` modifier fusion to avoid nested `div`s
  .pre-commit-config.yaml
  Package.resolved
  Package.swift
  Sources/TokamakCore/Modifiers/PaddingLayout.swift
  Sources/TokamakCore/Reflection/Pointers/MetadataOffset.swift
  Sources/TokamakStaticHTML/Views/HTML.swift
  Tests/TokamakStaticHTMLTests/HTMLTests.swift
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testOptional.1.txt
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testPaddingFusion.1.txt
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testPaddingFusion.2.txt
Labels: refactor

#412 Add a snapshot test for `Path` SVG layout
  .github/workflows/ci.yml
  Package.swift
  Sources/TokamakCore/MountedViews/MountedApp.swift
  Sources/TokamakCore/MountedViews/MountedCompositeView.swift
  Sources/TokamakCore/Reflection/Layouts/FieldDescriptor.swift
  Sources/TokamakCore/Shapes/Path.swift
  Sources/TokamakCore/Shapes/Path/Path.swift
  Sources/TokamakCore/Shapes/Path/PathLayout.swift
  Sources/TokamakCore/Shapes/Path/PathMutations.swift
  Sources/TokamakCore/Shapes/Path/PathSizing.swift
  Sources/TokamakStaticHTML/Views/Text/Text.swift
  Tests/TokamakStaticHTMLTests/LayoutTests.swift
  Tests/TokamakStaticHTMLTests/__Snapshots__/LayoutTests/testPath.1.png
  Tests/TokamakTests/GetSetStructTests.swift
  Tests/TokamakTests/ReconcilerStressTests.swift
Labels: DOM/HTML renderer, test suite

#414 Fix handling of stroked shapes
  Sources/TokamakCore/Shapes/ModifiedShapes.swift
  Sources/TokamakCore/Shapes/Path/Path.swift
  Sources/TokamakDemo/PathDemo.swift
  Sources/TokamakStaticHTML/Shapes/_ShapeView.swift
  Tests/TokamakStaticHTMLTests/LayoutTests.swift
  Tests/TokamakStaticHTMLTests/__Snapshots__/LayoutTests/testStrokedCircle.1.png
Labels: DOM/HTML renderer, bug

#413 Explicitly import CoreFoundation
  Sources/TokamakCore/Stubs/CGStubs.swift
Labels: refactor
