Repository TokamakUI/Tokamak, pull requests merged in 2021-01, with the labels that each got.

#349 Add a "bug report" issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#348 GTK shape support WIP
  Makefile
  Package.swift
  Sources/CGDK/CGDK-Bridging-Header.h
  Sources/CGDK/module.modulemap
  Sources/CGDK/termios-Header.h
  Sources/TokamakCore/Shapes/Path.swift
  Sources/TokamakGTK/GSignal.swift
  Sources/TokamakGTK/Modifiers/WidgetModifier.swift
  Sources/TokamakGTK/Shapes/Shape.swift
  Sources/TokamakStaticHTML/Shapes/Path.swift
Labels: GTK renderer, SwiftUI compatibility

#351 Add missing `Link` re-export to TokamakDOM
  Sources/TokamakDOM/Core.swift
Labels: SwiftUI compatibility, bug

#347 Build the GTK renderer on Ubuntu on CI
  .github/workflows/ci.yml
  .github/workflows/label.yml
  Makefile
  Package.resolved
  Package.swift
  Sources/TokamakCore/MountedViews/MountedElement.swift
  Sources/TokamakCore/MountedViews/MountedScene.swift
  Sources/TokamakCore/Views/Selectors/Picker.swift
  Sources/TokamakDemo/ColorDemo.swift
  Sources/TokamakGTK/Modifiers/LayoutModifiers.swift
  Sources/TokamakGTK/Widget.swift
  Sources/TokamakStaticHTML/Modifiers/ModifiedContent.swift
Labels: GTK renderer, continuous integration, dependencies

#352 Add @mortenbekditlevsen to the list of maintainers in `README.md`
  README.md
Labels: documentation

#356 Fixed a small issue with re-renderers being dropped
  Sources/TokamakCore/StackReconciler.swift
Labels: bug

#358 Removed an extra space that cause Safari to issue "Invalid value"
  Sources/TokamakStaticHTML/Shapes/Path.swift
Labels: bug

#355 Add support for shadow modifier
  NativeDemo/TokamakDemo.xcodeproj/project.pbxproj
  Sources/TokamakCore/Modifiers/ShadowLayout.swift
  Sources/TokamakDemo/ShadowDemo.swift
  Sources/TokamakDemo/TokamakDemo.swift
  Sources/TokamakStaticHTML/Modifiers/LayoutModifiers.swift
Labels: SwiftUI compatibility

#361 Added TextField support for GTK using GtkEntry
  Sources/TokamakGTK/Views/TextField.swift
Labels: GTK renderer

#359 Two infinite loop fixes
  Sources/TokamakCore/Environment/EnvironmentValues.swift
  Sources/TokamakCore/Tokens/Color.swift
Labels: bug

#363 Add GTK support for `SecureField`
  Sources/TokamakGTK/Views/TextField.swift
Labels: GTK renderer

#364 Fix crashes in views with optional content
  .vscode/tasks.json
  Package.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakCore/Views/AnyView.swift
  Sources/TokamakCore/Views/ViewBuilder.swift
  Sources/TokamakGTK/Views/TextField.swift
  Tests/TokamakStaticHTMLTests/HTMLTests.swift
Labels: bug

#365 Add a benchmark target and a script to run it
  .github/workflows/ci.yml
  .vscode/tasks.json
  Package.resolved
  Package.swift
  Sources/TokamakCore/Views/Text/TextEditor.swift
  Sources/TokamakStaticHTMLBenchmark/main.swift
  benchmark.sh
Labels: continuous integration

#360 Use `macos-latest` agent for the GTK build
  .github/workflows/ci.yml
Labels: continuous integration

#370 Replace uses of the Runtime library with stdlib
  Package.swift
  Sources/TokamakCore/App/App.swift
  Sources/TokamakCore/App/_AnyScene.swift
  Sources/TokamakCore/DynamicProperty.swift
  Sources/TokamakCore/MountedViews/MountedApp.swift
  Sources/TokamakCore/MountedViews/MountedCompositeView.swift
  Sources/TokamakCore/MountedViews/MountedElement.swift
  Sources/TokamakCore/MountedViews/MountedHostView.swift
  Sources/TokamakCore/MountedViews/MountedScene.swift
  Sources/TokamakCore/Reflection/TypeInfo.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakCore/Views/AnyView.swift
  Sources/TokamakCoreBenchmark/main.swift
  Sources/TokamakStaticHTML/Modifiers/ModifiedContent.swift
  benchmark.sh
Labels: bug, refactor

#371 Refactor environment injection, add a test
  Sources/TokamakCore/MountedViews/MountedElement.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakGTK/Views/NavigationView.swift
  Tests/TokamakTests/EnvironmentTests.swift
  Tests/TokamakTests/ReconcilerTests.swift
Labels: refactor, test suite

#373 Add David Hunt to the list of maintainers
  README.md
Labels: documentation

#372 Clean up metadata reflection code
  Package.resolved
  Package.swift
  Sources/TokamakCore/Modifiers/ModifiedContent.swift
  Sources/TokamakCore/MountedViews/MountedElement.swift
  Sources/TokamakCore/Reflection/Layouts/ExistentialContainter.swift
  Sources/TokamakCore/Reflection/Layouts/FieldDescriptor.swift
  Sources/TokamakCore/Reflection/Layouts/ProtocolTypeContainer.swift
  Sources/TokamakCore/Reflection/Layouts/StructMetadataLayout.swift
  Sources/TokamakCore/Reflection/Layouts/StructTypeDescriptor.swift
  Sources/TokamakCore/Reflection/Layouts/TargetTypeGenericContextDescriptorHeader.swift
  Sources/TokamakCore/Reflection/Layouts/ValueWitnessTable.swift
  Sources/TokamakCore/Reflection/Metadata/Metadata.swift
  Sources/TokamakCore/Reflection/Metadata/StructMetadata.swift
  Sources/TokamakCore/Reflection/Models/Kind.swift
  Sources/TokamakCore/Reflection/Models/PropertyInfo.swift
  Sources/TokamakCore/Reflection/Models/TypeInfo.swift
  Sources/TokamakCore/Reflection/Pointers/MetadataOffset.swift
  Sources/TokamakCore/Reflection/Pointers/Pointers.swift
  Sources/TokamakCore/Reflection/Pointers/RelativeVectorPointer.swift
  Sources/TokamakCore/Reflection/Utilities/GettersSetters.swift
  Sources/TokamakCore/Reflection/Utilities/Pointer+Extensions.swift
  Sources/TokamakCore/Reflection/typeConstructorName.swift
  Sources/TokamakCore/StackReconciler.swift
  Sources/TokamakCore/Styles/ButtonStyle.swift
  Sources/TokamakCore/Views/Containers/List.swift
  Sources/TokamakCore/Views/Image.swift
  Sources/TokamakCore/Views/Navigation/NavigationLink.swift
  Sources/TokamakCore/Views/Navigation/NavigationView.swift
  Sources/TokamakCore/Views/Selectors/Slider.swift
  Sources/TokamakCore/Views/Text/SecureField.swift
  Sources/TokamakCore/Views/Text/Text.swift
  Sources/TokamakCore/Views/Text/TextField.swift
  Sources/TokamakCoreBenchmark/main.swift
  Tests/TokamakTests/GetSetStructTests.swift
  Tests/TokamakTests/MetadataTests.swift
  Tests/TokamakTests/ValuePointerTests.swift
  Tests/TokamakTests/ValueWitnessTableTests.swift
Labels: refactor

#376 Update JavaScriptKit, OpenCombineJS dependencies
  Package.resolved
  Package.swift
Labels: dependencies

#377 Use upstream OpenCombine instead of a fork
  Package.resolved
  Package.swift
Labels: dependencies
