Repository TokamakUI/Tokamak, pull requests merged in 2022-05, with the labels that each got.

#477 Use stable `v5.6` version of `swiftwasm-action`
  .github/workflows/ci.yml
Labels: continuous integration

#481 Explicitly mention `carton` version in "Requirements"
  README.md
Labels: documentation

#482 Update JSKit dependency
  Package.resolved
  Package.swift
Labels: dependencies

#471 Experimental "React Fiber"-like Reconciler
  .github/workflows/ci.yml
  Package.swift
  Sources/TokamakCore/Fiber/Fiber.swift
  Sources/TokamakCore/Fiber/FiberElement.swift
  Sources/TokamakCore/Fiber/FiberReconciler.swift
  Sources/TokamakCore/Fiber/FiberRenderer.swift
  Sources/TokamakCore/Fiber/LayoutComputer.swift
  Sources/TokamakCore/Fiber/Mutation.swift
  Sources/TokamakCore/Fiber/ViewArguments.swift
  Sources/TokamakCore/Fiber/ViewVisitor.swift
  Sources/TokamakCore/Fiber/walk.swift
  Sources/TokamakCore/Modifiers/ViewModifier.swift
  Sources/TokamakCore/Reflection/Models/PropertyInfo.swift
  Sources/TokamakCore/Views/AnyView.swift
  Sources/TokamakCore/Views/Containers/ForEach.swift
  Sources/TokamakCore/Views/Containers/TupleView.swift
  Sources/TokamakCore/Views/Controls/Button.swift
  Sources/TokamakCore/Views/Layout/HStack.swift
  Sources/TokamakCore/Views/Layout/VStack.swift
  Sources/TokamakCore/Views/View.swift
  Sources/TokamakCore/Views/ViewBuilder.swift
  Sources/TokamakCoreBenchmark/main.swift
  Sources/TokamakDOM/DOMFiberRenderer.swift
  Sources/TokamakDOM/DOMRenderer.swift
  Sources/TokamakStaticHTML/StaticHTMLFiberRenderer.swift
  Sources/TokamakStaticHTMLBenchmark/main.swift
  Sources/TokamakTestRenderer/TestFiberRenderer.swift
  Tests/TokamakReconcilerTests/VisitorTests.swift
Labels: refactor

#484 Reenable macOS CI builds, using macOS 12 and Xcode 13.4
  .github/workflows/ci.yml
Labels: continuous integration

#486 Add html5 doctype to static renderer
  Sources/TokamakStaticHTML/StaticHTMLRenderer.swift
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testDoubleTitle.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testDoubleTitleModifier.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testFontStacks.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testFontStacks.2.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testHTMLSanitizer.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testHTMLSanitizer.2.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testMetaAll.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testMetaCharset.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testMetaCharsetModifier.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testOptional.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testPaddingFusion.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testPaddingFusion.2.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testPreferencePropagation.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testTitle.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testTitleModifier.1.html
Labels: enhancement

#487 Revert "Add html5 doctype to static renderer (#486)"
  Sources/TokamakStaticHTML/StaticHTMLRenderer.swift
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testDoubleTitle.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testDoubleTitleModifier.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testFontStacks.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testFontStacks.2.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testHTMLSanitizer.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testHTMLSanitizer.2.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testMetaAll.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testMetaCharset.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testMetaCharsetModifier.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testOptional.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testPaddingFusion.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testPaddingFusion.2.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testPreferencePropagation.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testTitle.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testTitleModifier.1.html
Labels: bug, continuous integration

#488 Clarify testing commands in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation

#453 Support `foregroundColor` for `TextField`
  Sources/TokamakCore/Views/Text/TextField.swift
  Sources/TokamakDOM/Views/Text/TextField.swift
Labels: SwiftUI compatibility, DOM/HTML renderer

#472 Custom Layout Engine for Fiber Reconciler
  Sources/TokamakCore/Environment/EnvironmentKey.swift
  Sources/TokamakCore/Environment/EnvironmentValues.swift
  Sources/TokamakCore/Fiber/AlignmentID.swift
  Sources/TokamakCore/Fiber/Fiber.swift
  Sources/TokamakCore/Fiber/FiberElement.swift
  Sources/TokamakCore/Fiber/FiberReconciler+TreeReducer.swift
  Sources/TokamakCore/Fiber/FiberReconciler.swift
  Sources/TokamakCore/Fiber/FiberRenderer.swift
  Sources/TokamakCore/Fiber/Layout/FlexLayoutComputer.swift
  Sources/TokamakCore/Fiber/Layout/FrameLayoutComputer.swift
  Sources/TokamakCore/Fiber/Layout/RootLayoutComputer.swift
  Sources/TokamakCore/Fiber/Layout/ShrinkWrapLayoutComputer.swift
  Sources/TokamakCore/Fiber/Layout/StackLayoutComputer.swift
  Sources/TokamakCore/Fiber/Layout/TextLayoutComputer.swift
  Sources/TokamakCore/Fiber/LayoutComputer.swift
  Sources/TokamakCore/Fiber/Mutation.swift
  Sources/TokamakCore/Fiber/ViewArguments.swift
  Sources/TokamakCore/Fiber/ViewGeometry.swift
  Sources/TokamakCore/Fiber/walk.swift
  Sources/TokamakCore/Modifiers/ModifiedContent.swift
  Sources/TokamakCore/Modifiers/ViewModifier.swift
  Sources/TokamakCore/Shapes/ShapeStyles/BackgroundStyle.swift
  Sources/TokamakCore/Shapes/ShapeStyles/ForegroundStyle.swift
  Sources/TokamakCore/Views/Containers/Group.swift
  Sources/TokamakCore/Views/Layout/HStack.swift
  Sources/TokamakCore/Views/Layout/VStack.swift
  Sources/TokamakCore/Views/Layout/ZStack.swift
  Sources/TokamakCore/Views/Text/Text.swift
  Sources/TokamakCoreBenchmark/main.swift
  Sources/TokamakDOM/DOMFiberRenderer.swift
  Sources/TokamakGTK/Views/Stack.swift
  Sources/TokamakStaticHTML/Modifiers/LayoutModifiers.swift
  Sources/TokamakStaticHTML/Modifiers/ViewModifier.swift
  Sources/TokamakStaticHTML/StaticHTMLFiberRenderer.swift
  Sources/TokamakStaticHTML/Views/Layout/HStack.swift
  Sources/TokamakStaticHTML/Views/Layout/VStack.swift
  Sources/TokamakStaticHTML/Views/Text/Text.swift
  Sources/TokamakTestRenderer/TestFiberRenderer.swift
  Tests/TokamakReconcilerTests/VisitorTests.swift
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testDoubleTitle.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testDoubleTitleModifier.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testFontStacks.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testFontStacks.2.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testHTMLSanitizer.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testHTMLSanitizer.2.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testMetaAll.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testMetaCharset.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testMetaCharsetModifier.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testTitle.1.html
  Tests/TokamakStaticHTMLTests/__Snapshots__/HTMLTests/testTitleModifier.1.html
Labels: enhancement

#493 Add support for 'Fiber' label in CI
  .github/workflows/label.yml
Labels: continuous integration, Fiber
